// Generated by CoffeeScript 1.12.7
(function() {
  window.html5support = {
    storage: function() {
      var error, p;
      try {
        p = 'localStorage';
        return p in window && window[p] !== null;
      } catch (error1) {
        error = error1;
        return false;
      }
    },
    getUserMedia: function(options, successCallback, errorCallback) {
      var f, wrappedSuccessCallback;
      f = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
      if (options === void 0) {
        return Boolean(f);
      }
      wrappedSuccessCallback = function(stream) {
        var url;
        url = window.URL || window.webkitURL;
        if (url) {
          stream = url.createObjectURL(stream);
        }
        return successCallback(stream);
      };
      return f.call(window.navigator, options, wrappedSuccessCallback, errorCallback);
    }
  };

}).call(this);
